---
env:
  contexts:
    - name: "Default Context"
      urls:
        - "http://first-webgoat-service.default/WebGoat"
      includePaths:
        - "http://first-webgoat-service.default/WebGoat.*"
      excludePaths: []
      authentication:
        method: "form"
        parameters:
          loginPageUrl: "http://first-webgoat-service.default/WebGoat/login"
          loginRequestUrl: "http://first-webgoat-service.default/WebGoat/login"
          loginRequestBody: "username={%username%}&password={%password%}"
        verification:
          method: "response"
          loggedInRegex: "Logout"
          loggedOutRegex: "Sign in"
          pollFrequency: 60
          pollUnits: "requests"
          pollUrl: ""
          pollPostData: ""
      sessionManagement:
        method: "cookie"
        parameters: {}
      users:
        - name: "admin"
          credentials:
            password: "cxadmin"
            username: "cxadmin"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
  - parameters:
      maxAlertsPerRule: 0
      scanOnlyInScope: true
      maxBodySizeInBytesToScan: 0
      enableTags: false
    rules: []
    name: "passiveScan-config"
    type: "passiveScan-config"
  - parameters:
      context: "Default Context"
      user: "admin"
      url: "http://first-webgoat-service.default/WebGoat"
      maxDuration: 0
      maxDepth: 0
      maxChildren: 0
    name: "spider"
    type: "spider"
    tests:
      - onFail: "INFO"
        statistic: "automation.spider.urls.added"
        site: ""
        operator: ">="
        value: 100
        name: "At least 100 URLs found"
        type: "stats"
  - parameters:
      context: "Default Context"
      user: "admin"
      url: "http://first-webgoat-service.default/WebGoat"
      maxDuration: 60
      maxCrawlDepth: 10
      numberOfBrowsers: 1
      runOnlyIfModern: false
    name: "spiderAjax"
    type: "spiderAjax"
    tests:
      - onFail: "INFO"
        statistic: "spiderAjax.urls.added"
        site: ""
        operator: ">="
        value: 100
        name: "At least 100 URLs found"
        type: "stats"
  - parameters: {}
    name: "passiveScan-wait"
    type: "passiveScan-wait"
  - parameters:
      context: "Default Context"
      user: "admin"
      policy: ""
      maxRuleDurationInMins: 0
      maxScanDurationInMins: 0
    policyDefinition:
      defaultStrength: "medium"
      defaultThreshold: "medium"
      rules: []
    name: "activeScan"
    type: "activeScan"
  - parameters:
      template: "traditional-json-plus"
      reportDir: "/zap/wrk"
      reportFile: ""
      reportTitle: "ZAP Scanning Report"
      reportDescription: ""
      displayReport: false
    risks:
      - "info"
      - "low"
      - "medium"
      - "high"
    confidences:
      - "falsepositive"
      - "low"
      - "medium"
      - "high"
      - "confirmed"
    name: "report"
    type: "report"
