name: DAST API Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-dast:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Scan IaC with kics
      - name: Checkmarx DAST GitHub Action
        uses: Checkmarx/dast-github-action@v1.0.0-beta
        env:
          CX_APIKEY: ${{ secrets.CX_ONE_API_KEY }}
        with:
          command: "api"
          config: 'WebGoat/WebTesting-ZapConf-AWS-Machine-2.yml'
          base_url: "localhost.cxast.net"
          environment_id: "c608a51a-ec4e-4eef-81c4-a0241737efd7"
          openapi: "swagger.yaml"
          project_id: "fd093dde-b64a-466f-b2cd-8bf141b4db94"
          fail_on: "HIGH"
          verbose: true
